config/routes.rb
Rails.application.routes.draw do
  require "sidekiq/web"

  namespace :admin do
    mount Sidekiq::Web => "/sidekiq"
    root "static_pages#index"
    resources :courses do
      resource :user_courses, only: [:show, :update]
    end
    resources :subjects
    resources :users
    resources :course_subjects, only: [:update]
  end
  root "static_pages#index"
  devise_for :users
  resources :user_courses do
    resources :user_subjects
  end
  resources :users, only: :show
end

app/controllers/admin/user_courses_controller.rb
class Admin::UserCoursesController < ApplicationController
  layout "admin_application"
  before_action :authenticate_user!
  before_action :verify_admin
  before_action :load_course, only: [:show, :update]
  load_and_authorize_resource

  def show
    @course.build_user_courses @course.users
  end

  def update
    @course.update_attributes course_params
    if @course.save
      flash[:success] = t "admin.user_courses.action_success"
      redirect_to admin_course_path @course
    else
      render :edit
    end
  end

  private
  def load_course
    @course = Course.find_by id: params[:course_id]
    unless @course
      flash[:danger] = t "admin.user_courses.course_not_found"
      redirect_to admin_courses_path
    end
  end

  def course_params
    params.require(:course)
      .permit user_courses_attributes: [:id, :user_id, :is_active, :_destroy]
  end
end

app/controllers/user_courses_controller.rb
class UserCoursesController < ApplicationController
  load_and_authorize_resource

  before_action :load_course, only: :show

  def index
    type = params[:type]
    get_user_courses = current_user.user_courses
    if type != "pending" && type != "started" && type != "finished"
      @user_courses = get_user_courses
    else
      @user_courses = get_user_courses.status_of_course Course.statuses[type]
    end
  end

  def show
     @course_subject = @user_course.course.course_subjects
    #@user_subjects = @user_course.user_subjects
    @subjects = @course.subjects.map do |subject|
      [subject, UserSubject.find_by_subject(@user_course.user.id, subject.id,
        @user_course.id), CourseSubject.of_course_and_subject(@course.id, subject.id)]
    end
    @trainer_in_course = @course.users.page(params[:page])
      .per Settings.pagination.per_page_member
    @count_all_subject = @user_course.course.course_subjects.count
  end

  private
  def load_course
    @course = @user_course.course
  end
end

app/views/user_courses/_process_subject.html.erb
<ul class="timeline timeline-custom">
  <li class="timeline-inverted">
    <div class="timeline-panel">
      <div class="timeline-heading">
        <h4 class="timeline-title"></h4>
        <div class="timeline-body">
          <% CourseSubject.statuses.each do |key,value| %>
            <% count = count_status_subject @course_subject, key %>
            <% subject = name_subject key %>
            <p class="btn btn-<%= type_status key %> btn-circle" >
              <p><%= subject %> <%= count %>/<%= @count_all_subject %></p>
            </p>
          <% end %>
        </div>
      </div>
    </div>
  </li>
</ul>

app/views/user_courses/_subjects_on_course.html.erb
<div class="col-md-12 top-20 padding-0">
  <div class="col-md-12">
    <div class="panel">
      <div class="panel-heading">
        <h3><%= t "subject.title_show_subject" %></h3>
      </div>
      <div class="panel-body">
        <div class="col-md-4">
          <ul class="timeline timeline-custom">
            <li class="timeline-inverted">
              <div class="timeline-panel">
                <div class="timeline-heading">
                  <h4 class="timeline-title"><%= t "subject.member" %>
                    <span class="badge"><%= course.users.size %></span></a>
                  </h4>
                  <div class="timeline-body">
                    <% @trainer_in_course.each do |trainer| %>
                      <p>
                        <%= trainer.name %>
                      </p>
                    <% end %>
                    <%= paginate @trainer_in_course %>
                  </div>
                </div>
              </div>
            </li>
          </ul>
          <%= render "process_subject" %>
        </div>
        <div class="col-md-8">
          <% subjects.each do |subject, user_subject, course_subject| %>
            <ul class="timeline">
              <li class="timeline-inverted">
                <div class="timeline-badge warning">
                  <i class="btn btn-<%= show_status_subject course_subject %> btn-circle btn-lg"></i>
                </div>
                <div class="timeline-panel">
                  <div class="timeline-heading">
                    <% if course.started? %>
                    <h4 class="timeline-title"><%= link_to subject.name,
                      user_course_user_subject_path(@user_course,user_subject) %>
                    </h4>
                    <% else %>
                      <h4 class="timeline-title"><%= subject.name %>
                      </h4>
                    <% end %>
                    <hr>
                    <div class="timeline-body">
                      <p><%= subject.description %>.</p>
                    </div>
                  </div>
                </div>
              </li>
            </ul>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/user_courses/index.html.erb
<section id="count" class = "login-section">
  <div class = "container">
    <div class = "row custom-row">
      <div class = "col-md-12">
        <div class="well well-sm">
          <strong>
            <%= t "course.title_show_course"%>
          </strong>
          <div class="btn-group">
            <%= link_to t("course.link_all"),
              user_courses_path(type: Settings.params_all),
              class: "btn btn-primary button" %>
            <%= link_to t("course.link_new"),
              user_courses_path(type: Settings.params_pending),
              class: "btn btn-primary button" %>
            <%= link_to t("course.link_started"),
              user_courses_path(type: Settings.params_started),
              class: "btn btn-primary button" %>
            <%= link_to t("course.link_finished"),
              user_courses_path(type: Settings.params_finished),
              class: "btn btn-primary button" %>
          </div>
        </div>
      </div>
    </div>
    <div class = "row custom-row">
      <div class = "col-md-12">
        <% @user_courses.each do |user_course|%>
          <div class = "col-md-4 custom-course">
            <div class="panel box-v7">
              <div class="panel-body">
                <div class="col-md-12 padding-0 box-v7-header">
                  <div class="col-md-12 padding-0">
                    <div class="col-md-10 padding-0">
                      <%= image_tag "avatar.png", class: "box-v7-avatar pull-left" %>
                      <h4>
                        <%= link_to user_course.course.name, user_course_path(user_course) %>
                      </h4>
                      <p>
                        <%= l user_course.course.start_date, format: :short %>
                        <span id="status"
                          class="label label-outline label-<%= show_status_course get_course_status user_course %>">
                          <%= user_course.course.status %>
                      </span>
                      </p>
                    </div>
                  </div>
                </div>
                <div class="col-md-12 padding-0 box-v7-body">
                  <p class = "course_description">
                    <%= user_course.course.description %>
                  </p>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/user_courses/show.html.erb
<section id="service" class = "user-section">
  <div id="mimin" class="dashboard topnav">
    <div class="row">
      <div class="col-md-12 top-20">
        <div class="col-md-12">
          <div class="panel">
            <div class="panel-body">
              <div class="col-md-12">
                <h3 class="animated fadeInLeft"><%= @course.name %></h3>
                <p class="animated fadeInDown">
                  <%= @course.description %>
                </p>
                <p class="animated fadeInLeft">
                  <%= @course.start_date %>
                  <span id="status"
                    class="label label-outline label-<%= show_status_course @course %>">
                    <%= @course.status %>
                  </span>
                </p>
              </div>
            </div>
          </div>
          <%= render partial: "subjects_on_course",
            locals: {subjects: @subjects, course: @course} %>
        </div>
      </div>
    </div>
  </div>
</section>