config/routes.rb
Rails.application.routes.draw do
  require "sidekiq/web"

  namespace :admin do
    mount Sidekiq::Web => "/sidekiq"
    root "static_pages#index"
    resources :courses do
      resource :user_courses, only: [:show, :update]
    end
    resources :subjects
    resources :users
    resources :course_subjects, only: [:update]
  end
  root "static_pages#index"
  devise_for :users
  resources :user_courses do
    resources :user_subjects
  end
  resources :users, only: :show
end

app/models/user_subject.rb
class UserSubject < ApplicationRecord
  include ActivityLog
  belongs_to :user
  belongs_to :user_course
  belongs_to :subject
  has_many :user_tasks, dependent: :destroy
  has_many :tasks, through: :subject

  enum status: {pending: 0, started: 1, finished: 2}

  tracked only: :update, owner: Proc.new{|controller| controller.current_user}

  accepts_nested_attributes_for :user_tasks, allow_destroy: true,
    reject_if: proc{|attribute| attribute[:task_id].nil?}

  scope :find_by_subject,->user_id, subject_id, user_course_id do
    find_by(user_id: user_id, subject_id: subject_id, user_course_id: user_course_id)
  end

  scope :count_status,->status do
    where(status: status).count(:status)
  end

  scope :count_subject,->user_id do
    where(user_id: user_id).count(:subject_id)
  end

  def all_activities
    PublicActivity::Activity.where(trackable_id: user_tasks.ids,
      trackable_type: UserTask.name).order("created_at desc")
  end

  def update_status
    task_count = tasks.count
    user_task_count = user_tasks.count
    if task_count == 0 || user_task_count <= 0
      pending!
    else
      if user_task_count < task_count
        started!
      elsif user_task_count >= task_count
        finished!
      end
    end
  end
end

app/controllers/user_subjects_controller.rb
class UserSubjectsController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource

  def show
    @user_course = @user_subject.user_course
    @tasks = @user_subject.subject.tasks
    @user_id = @user_subject.user_id
    @tasks.each do |task|
      @user_subject.user_tasks.find_or_initialize_by task_id: task.id,
        user_id: @user_id
    @count_user_task = @user_subject.user_tasks.count(:task_id)
    @count_task = @user_subject.subject.tasks.count(:subject_id)
    @activities = @user_subject.all_activities.page(params[:page])
    end

  end

  def update
    if @user_subject.update_attributes user_subject_params
       @user_subject.update_status
      flash[:success] = "update success"
    else
      flash[:danger] = "update error"
    end
    redirect_to :back
  end

  private
  def user_subject_params
    params.require(:user_subject).permit :user_id, :subject_id, :user_course_id,
     :status, user_tasks_attributes: [:id, :user_id, :task_id]
  end

end

app/views/user_subjects/_task_on_subject.html.erb
<div class="col-md-12 top-20 padding-0">
  <div class="col-md-12">
    <div class="panel">
      <div class="panel-heading">
        <h3><%= t "task.title_show_subject" %></h3>
      </div>
      <%= form_for @user_subject, url: user_course_user_subject_path(@user_course,
        @user_subject), method: :put do |f| %>
        <%= f.hidden_field :id %>
        <div class="panel-body">
          <div class="col-md-8">
            <ul class="timeline timeline-custom">
              <%= f.fields_for :user_tasks do |builder| %>
                <li class="timeline-inverted">
                  <div class="timeline-panel">
                    <div class="timeline-heading">
                      <h4 class="timeline-title">
                        <div class="timeline-body">
                          <% if builder.object.new_record? %>
                            <%= builder.hidden_field :user_id, value: @user_id %>
                            <%= builder.check_box :task_id, {checked: false},
                              builder.object.task.id, nil %>
                            <h4><%= builder.object.task.name %></h4>
                          <% else %>
                            <%= builder.hidden_field :user_id %>
                            <%= builder.check_box :task_id, {checked: true, disabled: true} %>
                            <h4><%= builder.object.task.name %></h4>
                          <% end %>
                        </div>
                      </h4>
                    </div>
                  </div>
                </li>
              <% end %>
              <div class="text-center">
                <% if @user_subject.finished? %>
                  <h3>
                    <span class="label label-success">
                      All Task Finish
                    </span>
                  </h3>
                <% else %>
                  <%= f.submit "Finish",
                    class: "btn btn-primary" if @user_subject.user == current_user %>
                <% end %>
              </div>
            </ul>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/user_subjects/show.html.erb
<section id="service" class = "user-section">
  <div id="mimin" class="dashboard topnav">
    <div class="row">
      <div class="col-md-12 top-20">
        <div class="col-md-12">
          <div class="panel">
            <div class="panel-body">
              <div class="col-md-12">
                <h3 class="animated fadeInLeft"><%= @user_subject.subject.name %></h3>
                <p class="animated fadeInDown">
                </p>
                <p class="animated fadeInLeft">
                  <span id="status"><%= @user_subject.status %></span>
                </p>
              </div>
            </div>
          </div>
          <div class="col-md-12 top-20 padding-0">
            <div class="col-md-8">
              <div class="panel">
                <div class="panel-heading">
                  <h3><%= t "task.task_activity" %></h3>
                </div>
                  <div class="panel-body">
                    <div class="col-md-8">
                      <ul class="list-group">
                        <% @activities.each do |activity| %>
                          <li>
                            <%= render_activity activity %>
                          </li>
                        <% end %>
                      </ul>
                    </div>
                  </div>
              </div>
            </div>
          </div>

          <%= render partial: "task_on_subject", locals: {tasks: @tasks} %>
        </div>
      </div>
    </div>
  </div>
</section>