config/routes.rb
Rails.application.routes.draw do
  require "sidekiq/web"

  namespace :admin do
    mount Sidekiq::Web => "/sidekiq"
    root "static_pages#index"
    resources :courses do
      resource :user_courses, only: [:show, :update]
    end
    resources :subjects
    resources :users
    resources :course_subjects, only: [:update]
  end
  root "static_pages#index"
  devise_for :users
  resources :user_courses do
    resources :user_subjects
  end
  resources :users, only: :show
end

app/controllers/admin/static_pages_controller.rb
class Admin::StaticPagesController < ApplicationController
  layout "admin_application"
  before_action :authenticate_user!
  before_action :verify_admin

  def index
    @courses = Course.all
    @subjects = Subject.all
    @users = User.all
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end
end

app/views/admin/static_pages/index.html.erb
<section id="service" class = "admin-section">
  <div class="container">
    <div class="row">
      <div class="col-md-4">
        <div class="panel box-v1 panel-primary">
          <div class="panel-heading border-none panel-heading-custom">
            <div class="col-md-6 col-sm-6 col-xs-6 text-left padding-0">
              <h4 class="text-left color-custom"><%= t ".menu_courses" %></h4>
            </div>
            <div class="col-md-6 col-sm-6 col-xs-6 text-right">
              <h4 class="color-custom">
                <span class="fa-mortar-board fa text-right"></span>
              </h4>
            </div>
          </div>
          <div class="panel-body text-center">
            <h1><%= @courses.count %></h1>
            <p><%= link_to t(".go_here"), admin_courses_path %></p>
            <hr/>
          </div>
        </div>
      </div>
      <div class="col-md-4">
        <div class="panel box-v1 panel-primary">
          <div class="panel-heading border-none panel-heading-custom">
            <div class="col-md-6 col-sm-6 col-xs-6 text-left padding-0">
              <h4 class="text-left color-custom"><%= t ".menu_subjects" %></h4>
            </div>
            <div class="col-md-6 col-sm-6 col-xs-6 text-right">
              <h4 class="color-custom">
                <span class="fa-book fa text-right"></span>
              </h4>
            </div>
          </div>
          <div class="panel-body text-center">
            <h1><%= @subjects.count %></h1>
            <p><%= link_to t(".go_here"), admin_subjects_path %></p>
            <hr/>
          </div>
        </div>
      </div>
      <div class="col-md-4">
        <div class="panel box-v1 panel-primary">
          <div class="panel-heading border-none panel-heading-custom">
            <div class="col-md-6 col-sm-6 col-xs-6 text-left padding-0">
              <h4 class="text-left color-custom"><%= t ".menu_users" %></h4>
            </div>
            <div class="col-md-6 col-sm-6 col-xs-6 text-right">
              <h4 class="color-custom">
                <span class="fa-user fa text-right"></span>
              </h4>
            </div>
          </div>
          <div class="panel-body text-center">
            <h1><%= @users.count %></h1>
            <p><%= link_to t(".go_here"), admin_users_path %></p>
            <hr/>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>